services:
  db:
    container_name: unifor_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: unifor